<#
.SYNOPSIS
Automatically generates frontend/config.js by fetching ApiEndpoint from CloudFormation stack outputs
and mapping account IDs and profiles from env.json.
#>

param (
    [string]$EnvFile = "env.json",
    [string]$StackName = "sg-automation-stack"
)

if (Test-Path $EnvFile) {
    $envConfig = Get-Content $EnvFile | ConvertFrom-Json
} else {
    Write-Host "Error: '$EnvFile' not found." -ForegroundColor Red
    Exit 1
}

$hubId = $envConfig.HUB_ACCOUNT_ID
$hubProfile = $envConfig.HUB_PROFILE
$region = $envConfig.REGION
$spokeProfiles = $envConfig.SPOKE_PROFILES

Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "Generating frontend/config.js automatically..." -ForegroundColor Cyan
Write-Host "Hub Profile: $hubProfile" -ForegroundColor Cyan
Write-Host "Fetching ApiEndpoint from CloudFormation stack '$StackName'..." -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan

# Fetch ApiEndpoint from CloudFormation using HubProfile from env.json
$apiEndpoint = cmd /c aws cloudformation describe-stacks `
    --stack-name $StackName `
    --profile $hubProfile `
    --region $region `
    --query "Stacks[0].Outputs[?OutputKey=='ApiEndpoint'].OutputValue" `
    --output text

$apiEndpoint = $apiEndpoint.Trim()

if (-not $apiEndpoint -or $apiEndpoint -eq "None") {
    Write-Host "Error: Failed to retrieve ApiEndpoint from stack '$StackName'." -ForegroundColor Red
    Exit 1
}

Write-Host "Discovered ApiEndpoint: $apiEndpoint" -ForegroundColor Green

# Build target accounts array
$targetAccounts = @()
$targetAccounts += [PSCustomObject]@{ id = $hubId; label = "Local Account ($hubId)" }

foreach ($item in $spokeProfiles) {
    if ($item.profile -and $item.accountId) {
        $prof = $item.profile
        $accId = $item.accountId
        Write-Host "Mapped Profile '$prof' -> Account ID: $accId" -ForegroundColor Gray
        $targetAccounts += [PSCustomObject]@{ id = $accId; label = "$prof ($accId)" }
    } elseif ($item.profile) {
        $prof = $item.profile
        Write-Host "Resolving Account ID for profile '$prof' via AWS CLI..." -ForegroundColor Gray
        $accId = cmd /c aws sts get-caller-identity `
            --profile $prof `
            --query "Account" `
            --output text 2>$null

        if ($accId) { $accId = $accId.Trim() }

        if ($accId -and $accId -ne "None") {
            $targetAccounts += [PSCustomObject]@{ id = $accId; label = "$prof ($accId)" }
        } else {
            $targetAccounts += [PSCustomObject]@{ id = $prof; label = "$prof" }
        }
    } else {
        $targetAccounts += [PSCustomObject]@{ id = $item; label = "$item" }
    }
}

# Format targetAccounts JSON
$targetAccountsJson = $targetAccounts | ConvertTo-Json -Depth 3

# Generate JS content
$configJsContent = @"
/**
 * Application AWS Configuration
 * Automatically generated by scripts/generate-frontend-config.ps1
 */
window.APP_CONFIG = {
  apiEndpoint: "$apiEndpoint",
  defaultRegion: "$region",
  localAccountId: "$hubId",
  defaultRoleName: "SgAutomationCrossAccountRole",
  targetAccounts: $targetAccountsJson
};
"@

$configFile = "$PSScriptRoot/../frontend/config.js"
$utf8Encoding = New-Object System.Text.UTF8Encoding $false
[System.IO.File]::WriteAllText($configFile, $configJsContent, $utf8Encoding)
Write-Host "`nSuccessfully generated '$configFile' in clean UTF-8!" -ForegroundColor Green
